# Generated by Django 5.0.6 on 2024-06-01 06:44

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='E-mail')),
                ('DateOfBirth', models.DateField(verbose_name='Дата рождения')),
                ('saleCard', models.CharField(max_length=15, null=True, verbose_name='Скидочная карта')),
                ('comments', models.TextField(null=True, verbose_name='Примечание')),
                ('serialNumber', models.CharField(max_length=9, null=True, verbose_name='Серия/Номер')),
                ('identificationNumber', models.CharField(max_length=100, null=True, verbose_name='Индефикационный номер')),
                ('issued', models.CharField(max_length=100, null=True, verbose_name='Кем выдан')),
                ('dateIssued', models.DateField(verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=40, null=True, verbose_name='Тип устройства')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
            },
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStatus', models.CharField(max_length=20, verbose_name='Статус')),
                ('colorStatus', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
                ('descriptionStatus', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, verbose_name='Название компании')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('site', models.CharField(max_length=100, verbose_name='Сайт')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('currency', models.CharField(max_length=100, verbose_name='Валюта')),
                ('bik', models.CharField(max_length=8, verbose_name='БИК банка')),
                ('checkingAccount', models.CharField(max_length=24, verbose_name='Расчетный счет')),
                ('unp', models.CharField(max_length=100, verbose_name='УНП')),
                ('bankName', models.CharField(max_length=50, verbose_name='Банк')),
                ('logo', models.ImageField(null=True, upload_to='static/img/company/', verbose_name='Логотип')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshopName', models.CharField(max_length=100, verbose_name='Название мастерской')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='E-mail')),
                ('WorkShopColor', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.company', verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Мастерская',
                'verbose_name_plural': 'Мастерские',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True, verbose_name='Комментарии к заказу')),
                ('malfunction', models.CharField(max_length=100, verbose_name='Неисправность')),
                ('modelDevice', models.CharField(max_length=100, null=True, verbose_name='Модель устройства')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет устройства')),
                ('equipment', models.CharField(max_length=100, null=True, verbose_name='Комплектация')),
                ('Appearance', models.CharField(max_length=100, null=True, verbose_name='Внешний вид')),
                ('processor', models.CharField(max_length=100, null=True, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=100, null=True, verbose_name='Оперативная память')),
                ('gpu', models.CharField(max_length=100, null=True, verbose_name='Видеокарта')),
                ('storageDevice', models.CharField(max_length=100, null=True, verbose_name='Накопитель')),
                ('estimatedСost', models.IntegerField(null=True, verbose_name='Ориентировочная стоимость')),
                ('deadline', models.DateField(verbose_name='Крайний срок')),
                ('urgently', models.BooleanField(default=False, verbose_name='Срочно')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.customerorder', verbose_name='Заказчик')),
                ('typeDevice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.devices', verbose_name='Тип устройства')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.statusorder', verbose_name='Статус')),
                ('workShop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.workshop', verbose_name='Мастерская')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
