# Generated by Django 5.0.6 on 2024-06-01 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOrder', models.CharField(max_length=100, verbose_name='Тип заказа')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='typeOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.typeorders', verbose_name='Тип Заказа'),
        ),
    ]
