# Generated by Django 5.0.6 on 2024-06-01 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0002_brand_employees_positions_typeorders_order_typeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOrder', models.CharField(max_length=100, verbose_name='Тип заказа')),
                ('descriptionTypeOrder', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип заказа',
                'verbose_name_plural': 'Типы заказа',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='typeOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.typeorder', verbose_name='Тип Заказа'),
        ),
        migrations.DeleteModel(
            name='TypeOrders',
        ),
    ]
