# Generated by Django 5.0.6 on 2024-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0003_typeorder_alter_order_typeorder_delete_typeorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeorder',
            name='descriptionTypeOrder',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
    ]
