# Generated by Django 5.0.6 on 2024-06-01 08:00

import databaseCRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0005_order_datecreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateCreate',
            field=models.DateTimeField(default=databaseCRM.models.default_datetime, null=True, verbose_name='Дата создания'),
        ),
    ]
