# Generated by Django 5.0.6 on 2024-06-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0006_alter_order_datecreate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AddField(
            model_name='employees',
            name='address',
            field=models.CharField(max_length=30, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='employees',
            name='birthday',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=30, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='employees',
            name='nameEmployees',
            field=models.CharField(max_length=30, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='employees',
            name='photo',
            field=models.CharField(max_length=30, null=True, verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='employees',
            name='positions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.positions', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='databaseCRM.employees', verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='databaseCRM.employees', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='positions',
            name='namePosition',
            field=models.CharField(max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
