# Generated by Django 5.0.6 on 2024-06-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0007_alter_employees_options_alter_positions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
