# Generated by Django 5.0.6 on 2024-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0008_alter_employees_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(max_length=30, null=True, upload_to='static/img/company/staff', verbose_name='Фотография'),
        ),
    ]
