# Generated by Django 5.0.6 on 2024-06-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0009_alter_employees_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/img/company/staff', verbose_name='Фотография'),
        ),
    ]
