# Generated by Django 5.0.6 on 2024-06-01 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0010_alter_employees_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AddField(
            model_name='brand',
            name='nameBrand',
            field=models.CharField(max_length=100, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.brand', verbose_name='Статус'),
        ),
    ]
