# Generated by Django 5.0.6 on 2024-06-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0011_alter_brand_options_brand_namebrand_order_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.brand', verbose_name='Производитель'),
        ),
    ]
