# Generated by Django 5.0.6 on 2024-06-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0012_alter_order_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='akts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100, null=True, verbose_name='Работа/услуга')),
                ('count', models.IntegerField(verbose_name='Колличество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('summ', models.FloatField(default=1, verbose_name='Сумма')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseCRM.order', verbose_name='Заказ')),
            ],
        ),
    ]
