# Generated by Django 5.0.6 on 2024-06-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseCRM', '0013_akts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akts',
            name='summ',
            field=models.FloatField(default=4, verbose_name='Сумма'),
        ),
    ]
